# Generated by Django 4.2.6 on 2023-10-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_applications_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
