# Generated by Django 4.2.6 on 2023-11-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_applications_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ['-create_time'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='applications',
            name='status',
            field=models.BooleanField(blank=True, choices=[(0, 'В ожидании'), (1, 'Выполнено')], default=0),
        ),
        migrations.AlterField(
            model_name='applications',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания заявки'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Телефон'),
        ),
    ]
