# Generated by Django 4.2.6 on 2023-11-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_applications_options_applications_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.TextField(blank=True, choices=[('В ожидании', 'Awaiting'), ('Выполнено', 'Completed'), ('Отменено', 'Canceled')], default='В ожидании'),
        ),
    ]
